redberry/models/post.py
import collections
from sqlalchemy import event

from redberry.models import db, RedModel, generate_slug


categories_posts = db.Table('redberry_categories_posts',
                              db.Column('category_id', db.Integer, db.ForeignKey('redberry_categories.id'), nullable=False),
                              db.Column('post_id', db.Integer, db.ForeignKey('redberry_posts.id'), nullable=False),
                              db.PrimaryKeyConstraint('category_id', 'post_id'))


class RedPost(RedModel):
    __tablename__ = 'redberry_posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    slug = db.Column(db.String(255))
    content = db.Column(db.Text)
    summary = db.Column(db.Text)
    hero_image = db.Column(db.Text)
    published = db.Column(db.Boolean, default=True, index=True)
    created_at = db.Column(db.TIMESTAMP, server_default=db.func.current_timestamp())
    updated_at = db.Column(db.TIMESTAMP, server_default=db.func.current_timestamp(), onupdate=db.func.current_timestamp())

    categories = db.relationship("RedCategory", secondary=categories_posts, backref='posts')

    @classmethod
    def all_published(cls):
        return cls.query.filter_by(published=True).order_by('created_at DESC').all()

    def keywords(self, num=5):

        words_only = self.strip_tags(self.content, strip_punctuation=True)
        words = words_only.split()

        counter = collections.Counter(words)
        common = counter.most_common()

        keywords = []

        INSIGNIFICANT_WORDS = ('should', 'which', 'therefore')

        for word in common:
            lower_word = word[0].lower()
            if len(lower_word) > 4 and lower_word not in INSIGNIFICANT_WORDS:
                keywords.append(lower_word)

            if len(keywords) >= num:
                break

        return ", ".join(keywords)


event.listen(RedPost.title, 'set', generate_slug, retval=False)

redberry/forms/post.py
from flask_wtf import FlaskForm
from wtforms import validators, StringField, BooleanField, TextAreaField, SelectMultipleField


class PostForm(FlaskForm):
    title = StringField('Title', [validators.DataRequired()])
    summary = TextAreaField('Summary')
    content = TextAreaField('Content')
    hero_image = StringField('Hero Image')
    categories = SelectMultipleField('Categories', coerce=int)
    published = BooleanField('Published')

redberry/blueprint.py
import os
import functools
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask.ext.login import current_user

REDBERRY_ROOT = os.path.dirname(os.path.realpath(__file__))

cms = Blueprint('redberry', __name__, template_folder='templates', static_folder='static/redberry')
cms.config = {
    'db': None,
    'meta': {
        'title': None
    }
}


##############
# Jinja Filters
###############
@cms.app_template_filter()
def pretty_date(dttm):
    return dttm.strftime("%m/%d")

@cms.app_template_filter()
def date(dttm):
    return dttm.strftime('%Y-%m-%d')


########
# Config
########
# Automatically called once when the Blueprint is registered on the app.
@cms.record_once
def init_redberry(state):
    config = state.app.config.get("redberry.config")

    if config is None:
        raise Exception("Redberry expects you to provide a dict in the redberry.config setting for your app")

    if 'db' not in config:
        raise Exception("Redberry expects you to provide an SQLAlchemy object in redberry.config['db']")

    cms.config['db'] = config['db']
    cms.config['meta']['title'] = config.get('title') or "Redberry CMS - a Flask blog blueprint"

    from redberry.utils.logger import init_logger
    init_logger()

    from redberry.models.migrate import RedMigrator
    migrator = RedMigrator()
    migrator.do_migration()
    migrator.initialize_samples()


def admin_login_required(method):
    def is_admin(user):
        if isinstance(user.is_admin, bool):
            return user.is_admin
        else:
            return user.is_admin()

    @functools.wraps(method)
    def wrapper(*args, **kwargs):
        if not current_user.is_authenticated:
            flash("This section is for logged in users only.", 'warning')
            return redirect(url_for('redberry.home'))

        if not hasattr(current_user, 'is_admin'):
            flash("Redberry expects your user instance to implement an `is_admin` boolean attribute "
                  "or an `is_admin()` method.", 'warning')
            return redirect(url_for('redberry.home'))

        if not is_admin(current_user):
            flash("This section is for admin users only.", 'warning')
            return redirect(url_for('redberry.home'))

        return method(*args, **kwargs)

    return wrapper


############
# CMS ROUTES
############
@cms.route('/')
@cms.route('.amp/', endpoint='home_amp')
def home():
    from redberry.models import RedPost
    posts = RedPost.all_published()
    return render_redberry('redberry/index.html', posts=posts)


@cms.route('/<slug>')
@cms.route('/<slug>.amp', endpoint='show_post_amp')
def show_post(slug):
    from redberry.models import RedPost
    post = RedPost.query.filter_by(slug=slug).first()
    if not post:
        flash("Post not found!", 'danger')
        return redirect(url_for('redberry.home'))

    return render_redberry('redberry/post.html', post=post)


@cms.route('/category/<category_slug>')
@cms.route('/category/<category_slug>.amp', endpoint='show_category_amp')
def show_category(category_slug):
    from redberry.models import RedCategory
    category = RedCategory.query.filter_by(slug=category_slug).first()
    if not category:
        flash("Category not found!", 'danger')
        return redirect(url_for('redberry.home'))
    return render_redberry('redberry/category.html', category=category)


@cms.route('/sitemap')
def build_sitemap():
    from redberry.models import RedPost, RedCategory
    from apesmit import Sitemap
    sm = Sitemap(changefreq='weekly')

    for post in RedPost.all_published():
        sm.add(url_for('redberry.show_post', slug=post.slug, _external=True), lastmod=post.updated_at.date())

    for category in RedCategory.query.all():
        sm.add(url_for('redberry.show_category', category_slug=category.slug, _external=True), lastmod=category.updated_at.date())

    with open(os.path.join(REDBERRY_ROOT, 'static', 'redberry', 'sitemap.xml'), 'w') as f:
        sm.write(f)

    flash("Sitemap created.", 'success')
    return redirect(url_for('redberry.home'))


##############
# ADMIN ROUTES
##############
@cms.route('/admin', methods=['GET'], defaults={'model_name': 'category'})
@cms.route('/admin/<string:model_name>', methods=['GET'])
@admin_login_required
def admin(model_name):
    from redberry.models import RedCategory, RedPost

    if model_name == 'category':
        objects = RedCategory.query.all()

    elif model_name == 'post':
        objects = RedPost.query.all()

    return render_template('redberry/admin/index.html', objects=objects, model_name=model_name)


@cms.route('/admin/<string:model_name>/new', methods=['GET', 'POST'])
@admin_login_required
def new_record(model_name):
    from redberry.models import RedCategory, RedPost
    from redberry.forms import CategoryForm, PostForm

    if model_name == 'category':
        form = CategoryForm()
        new_record = RedCategory()

    elif model_name == 'post':
        form = PostForm()
        new_record = RedPost()

        # Convert category ids into objects for saving in the relationship.
        if form.categories.data:
            form.categories.data = RedCategory.query.filter(RedCategory.id.in_(form.categories.data)).all()
            form.categories.choices = [(c, c.title) for c in RedCategory.sorted()]
        else:
            form.categories.choices = [(c.id, c.title) for c in RedCategory.sorted()]

    if form.validate_on_submit():
        form.populate_obj(new_record)

        cms.config['db'].session.add(new_record)
        cms.config['db'].session.flush()

        build_sitemap()

        flash("Saved %s %s" % (model_name, new_record.id), 'success')
        return redirect(url_for('redberry.admin', model_name=model_name))

    return render_template('redberry/admin/form.html', form=form, model_name=model_name)


@cms.route('/admin/<string:model_name>/<string:slug>', methods=['GET', 'POST'])
@admin_login_required
def edit_record(model_name, slug):
    from redberry.models import RedCategory, RedPost
    from redberry.forms import CategoryForm, PostForm

    if model_name == 'category':
        record = RedCategory.query.filter_by(slug=slug).first()
        form = CategoryForm(obj=record)

    elif model_name == 'post':
        record = RedPost.query.filter_by(slug=slug).first()
        form = PostForm(obj=record)

        # Convert category ids into objects for saving in the relationship.
        form.categories.choices = [(c.id, c.title) for c in RedCategory.sorted()]
        if record.categories and request.method == 'GET':
            form.categories.data = [c.id for c in record.categories]

    if not record:
        flash("%s not found!" % model_name.title(), 'danger')
        return redirect(url_for('redberry.admin'))

    if form.validate_on_submit():

        if model_name == 'post' and form.categories.data:
            form.categories.data = RedCategory.query.filter(RedCategory.id.in_(form.categories.data)).all()

        form.populate_obj(record)
        cms.config['db'].session.flush()
        build_sitemap()
        flash("Saved %s %s" % (model_name, record.id), 'success')
        return redirect(url_for('redberry.admin', model_name=model_name))

    elif request.values.get('_method') == 'DELETE':
        record.delete()
        build_sitemap()
        flash("Deleted %s" % model_name, 'success')
        return redirect(url_for('redberry.admin', model_name=model_name))

    return render_template('redberry/admin/form.html', form=form, object=record, model_name=model_name)


##############
# ADMIN ROUTES
##############
def render_redberry(template_name, **kwargs):

    # For Accelerated Mobile Pages (AMP, ref: https://www.ampproject.org) use templates with a .amp suffix
    if '.amp' in request.path:
        kwargs['render_amp'] = True

    kwargs['meta'] = cms.config['meta']

    return render_template(template_name, **kwargs)

redberry/templates/redberry/admin/_categories.html
<h1>
    Categories
    <a class="btn btn-lg btn-success pull-right" href="{{ url_for('redberry.new_record', model_name='category') }}">
        <span class="glyphicon glyphicon-plus"></span>
        Add New
    </a>
</h1>

{% if not objects %}
    No categories yet.
{% else %}
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Description</th>
                <th>Created</th>
                <th>Action</th>
            </tr>
        </thead>

        <tbody>
            {% for category in objects %}
                <tr>
                    <td>{{ category.id }}</td>
                    <td><a href="{{ url_for('redberry.show_category', category_slug=category.slug) }}" target="_blank">{{ category.title | safe }}</a></td>
                    <td>{{ category.summarise(20) }}</td>
                    <td>{{ category.created_at | pretty_date }}</td>
                    <td>
                        <a href="{{ url_for('redberry.edit_record', model_name='category', slug=category.slug) }}">Edit</a>
                        <a href="{{ url_for('redberry.edit_record', model_name='category', slug=category.slug) }}" data-method="delete">
                            Delete
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>

    </table>
{% endif %}

redberry/templates/redberry/admin/_posts.html
{% import "redberry/_macros.html" as macros %}

<h1>
    Posts
    <a class="btn btn-lg btn-success pull-right" href="{{ url_for('redberry.new_record', model_name='post') }}">
        <span class="glyphicon glyphicon-plus"></span>
        Add New
    </a>
</h1>

{% if not objects %}
    No posts yet.
{% else %}
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Image</th>
                <th>Summary</th>
                <th>Published</th>
                <th>Created</th>
                <th>Action</th>
            </tr>
        </thead>

        <tbody>
            {% for post in objects %}
                <tr>
                    <td>{{ post.id }}</td>
                    <td>
                        {% if post.hero_image %}
                            <img src="{{ post.hero_image }}" width="100"/>
                        {% else %}
                            No image
                        {% endif %}
                    </td>
                    <td>
                        <div>
                            <a href="{{ url_for('redberry.show_post', slug=post.slug) }}" target="_blank">{{ post.title }}</a>
                        </div>
                        {{ post.summary | safe }}
                    </td>
                    <td>{{ macros.true_or_false(post.published) }}</td>
                    <td>{{ post.created_at | pretty_date }}</td>
                    <td>
                        <a href="{{ url_for('redberry.edit_record', model_name='post', slug=post.slug) }}">Edit</a>
                        <a href="{{ url_for('redberry.edit_record', model_name='post', slug=post.slug) }}" data-method="delete">
                            Delete
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>

    </table>
{% endif %}

redberry/templates/redberry/admin/form.html
{% extends "redberry/admin/index.html" %}

{% block head %}
    <title>Admin</title>
    <link href="{{ url_for('redberry.static', filename='css/trumbowyg.min.css')}}" rel="stylesheet">
{% endblock %}

{% block admin_content %}

    <div class="panel panel-default">
        <div class="panel-body">
            <form method="POST">
                {{ form.csrf_token }}

                {% for field in form %}
                    {% if field.name != 'csrf_token' %}
                        <div class="form-group {% if field.errors %}has-error{% endif %}">
                            {{ field.label }}
                            {% if field.type == 'TextAreaField' %}
                                <div class="rich-editable" id="{{ field.name }}">{{ field.data | safe }}</div>
                                {{ field(class='hide') }}
                            {% else %}
                                {{ field(class='form-control') }}
                            {% endif %}

                            <span class="help-block">
                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                            </span>
                        </div>

                    {% endif %}
                {% endfor %}

                <button type="submit" class="btn btn-lg btn-success">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{{ url_for('redberry.static', filename='js/trumbowyg.min.js')}}"></script>
<script type="text/javascript" src="{{ url_for('redberry.static', filename='js/trumbowyg.preformatted.min.js')}}"></script>
<script type="text/javascript" src="{{ url_for('redberry.static', filename='js/trumbowyg.table.min.js')}}"></script>
<script type="text/javascript" src="{{ url_for('redberry.static', filename='js/redberry_admin.js')}}"></script>
<script type="text/javascript">
    $.trumbowyg.svgPath = "{{ url_for('redberry.static', filename='svg/icons.svg') }}"
</script>
{% endblock %}

redberry/templates/redberry/admin/index.html
{% extends "redberry/_base.html" %}

{% block head %}
    <title>Admin Panel | {{ model_name.title() }}</title>
{% endblock %}

{% block content %}

    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{{ url_for('redberry.admin') }}" >Redberry Admin</a>
                </li>
                <li>
                    <a href="{{ url_for('redberry.home') }}">View Site</a>
                </li>
            </ul>
        </div>
    </nav>


    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <ul class="red-admin-sidebar">
                    <li class="{% if model_name == 'category' %}active{% endif %}">
                        <a href="{{ url_for('redberry.admin', model_name='category') }}">Categories</a>
                    </li>
                    <li class="{% if model_name == 'post' %}active{% endif %}">
                        <a href="{{ url_for('redberry.admin', model_name='post') }}">Posts</a>
                    </li>
                </ul>
            </div>

            <div class="col-md-9">
                {% block admin_content %}
                    {% if model_name == 'category' %}
                        {% include 'redberry/admin/_categories.html' %}

                    {% elif model_name == 'post' %}
                        {% include 'redberry/admin/_posts.html' %}

                    {% endif %}
                {% endblock %}
            </div>

        </div>
    </div>


{% endblock %}

{% block javascript %}
    <script src="{{ url_for('redberry.static', filename='js/restful.min.js') }}"></script>
    <script>
        // Initialize RestfulLinks with default options
        $(document).ready(function(){
            $('body').restfullinks()
        })
    </script>
{% endblock %}